### ISSUE TITLE
Error on Shell Command `cainstall`

### ISSUE THREAD

**Issue by forstjiri** [cakemanager/cakephp-cakeadmin#9]
Hi, i have cakephp 3.1 and i get this error:

```
Migrating Settings Tables...
Exception: SQLSTATE[42000]: Syntax error or access violation: 1101 BLOB/TEXT column 'value' can't have a default value in [/var/www/html/dochazkovysystem2015/app/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php, line 297]
2015-11-13 16:44:16 Error: [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1101 BLOB/TEXT column 'value' can't have a default value
Stack Trace:
#0 /var/www/html/dochazkovysystem2015/app/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(297): PDO->exec('CREATE TABLE `s...')
#1 /var/www/html/dochazkovysystem2015/app/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/MysqlAdapter.php(296): Phinx\Db\Adapter\PdoAdapter->execute('CREATE TABLE `s...')
#2 /var/www/html/dochazkovysystem2015/app/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(550): Phinx\Db\Adapter\MysqlAdapter->createTable(Object(Phinx\Db\Table))
#3 /var/www/html/dochazkovysystem2015/app/vendor/cakemanager/cakephp-settings/config/Migrations/20150126111319_settings_initial.php(62): Phinx\Db\Table->create()
#4 /var/www/html/dochazkovysystem2015/app/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(116): SettingsInitial->up()
#5 /var/www/html/dochazkovysystem2015/app/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(210): Phinx\Migration\Manager\Environment->executeMigration(Object(SettingsInitial), 'up')
#6 /var/www/html/dochazkovysystem2015/app/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(186): Phinx\Migration\Manager->executeMigration('default', Object(SettingsInitial), 'up')
#7 [internal function]: Phinx\Migration\Manager->migrate('default', NULL)
#8 /var/www/html/dochazkovysystem2015/app/vendor/cakephp/migrations/src/Migrations.php(200): call_user_func_array(Array, Array)
#9 /var/www/html/dochazkovysystem2015/app/vendor/cakephp/migrations/src/Migrations.php(114): Migrations\Migrations->run('migrate', Array, Object(Symfony\Component\Console\Input\ArrayInput))
#10 /var/www/html/dochazkovysystem2015/app/vendor/cakemanager/cakephp-cakeadmin/src/Shell/CainstallShell.php(52): Migrations\Migrations->migrate(Array)
#11 /var/www/html/dochazkovysystem2015/app/vendor/cakemanager/cakephp-cakeadmin/src/Shell/CainstallShell.php(35): CakeAdmin\Shell\CainstallShell->migrate('Settings')
#12 [internal function]: CakeAdmin\Shell\CainstallShell->main()
#13 /var/www/html/dochazkovysystem2015/app/vendor/cakephp/cakephp/src/Console/Shell.php(447): call_user_func_array(Array, Array)
#14 /var/www/html/dochazkovysystem2015/app/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(212): Cake\Console\Shell->runCommand(Array, true, Array)
#15 /var/www/html/dochazkovysystem2015/app/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(179): Cake\Console\ShellDispatcher->_dispatch(Array)
#16 /var/www/html/dochazkovysystem2015/app/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(126): Cake\Console\ShellDispatcher->dispatch(Array)
#17 /var/www/html/dochazkovysystem2015/app/bin/cake.php(20): Cake\Console\ShellDispatcher::run(Array)
#18 {main}
```

**Comment by bobmulder** [comment]
Hi @aiphee,

Thank you for your report. I will confirm at as soon as possible. By then we will look for a fix. Hang on!

**Comment by bobmulder** [comment]
Hi @aiphee, can you confirm this is fixed now? Please let me know!

**Comment by forstjiri** [comment]
Ok, i did this in setting migrations

```
            ->addColumn('value', 'text', [
//                'default' => '',
                'null' => true
            ])
            ->addColumn('description', 'text', [
//                'default' => '',
                'null' => true
            ])
```

And now it works :)

**Comment by bobmulder** [comment]
I hoped using the latest commit would work. For me it did...
